language: ruby
rvm:
  - 2.3.3

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE "future-perfect";' -U postgres
  - psql -c "CREATE USER \"future-perfect\" WITH PASSWORD '${DATABASE_PASSWORD}';" -U postgres

script:
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake spec

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  run:
    - "rake db:migrate"
  skip_cleanup: true # keep generated assets

after_script:
  - curl -o trigger.sh https://raw.githubusercontent.com/Arthaey/travis-build-history-badges/master/bin/trigger_badges_updates.sh
  - sh trigger.sh
